enum Screens {
    MAIN_APP = 'MAIN_APP',

    ONBOARDING = 'ONBOARDING_SCREEN',
    AUTH = 'AUTH_SCREEN',
    TARIF = 'TARIF_SCREEN',
    RESERVATION = 'RESERVATION_SCREEN',
    RESERVATION_LIST = 'RESERVATION_LIST_SCREEN',
    RESERVATION_DETAILS = 'RESERVATION_DETAILS_SCREEN',
    WEB_VIEW = 'WEB_VIEW_SCREEN',

    MAIN_ENABLED_SCREEN = 'MAIN_ENABLED_SCREEN',

    // Tabs
    HOME = 'HOME_SCREEN',
    QR = 'QR_SCREEN',
    SETTINGS = 'SETTINGS_SCREEN',
}

export default Screens;
